# Generated by Django 4.2 on 2024-12-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('lessee_name', models.CharField(max_length=255)),
                ('lessee_cpr_number', models.CharField(max_length=50)),
                ('lessor_name', models.CharField(max_length=255)),
                ('lessor_cr_number', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incubator_number', models.CharField(max_length=20)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('lease_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lamx.leasecontract')),
            ],
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['contract_number'], name='lamx_leasec_contrac_85eb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['lessee_name'], name='lamx_leasec_lessee__723275_idx'),
        ),
    ]
