# Generated by Django 4.2 on 2024-12-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
