# Generated by Django 4.2 on 2024-12-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0002_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='actual_rent_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=160.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='business_incubator_number',
            field=models.CharField(default='0151', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='contract_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='dispute_resolution',
            field=models.TextField(blank=True, default='Dispute resolution terms.', null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='incubator_address',
            field=models.TextField(blank=True, default='Default Incubator Address', null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='lessee_authorized_signatory',
            field=models.CharField(blank=True, default='Authorized Signatory', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='lessee_commercial_name',
            field=models.CharField(blank=True, default='Commercial Name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='lessee_commercial_registry_number',
            field=models.CharField(blank=True, default='000000', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='lessee_personal_id',
            field=models.CharField(blank=True, default='0000', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='lessee_title',
            field=models.CharField(blank=True, default='Title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='lessor_authorized_signatory',
            field=models.CharField(blank=True, default='Lessor Signatory', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='lessor_title',
            field=models.CharField(blank=True, default='Partner', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='modification_terms',
            field=models.TextField(blank=True, default='Modification terms here.', null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='monthly_rent_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=70.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='office_actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=160.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='payment_obligations',
            field=models.TextField(blank=True, default='Payment details here.', null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='support_stop_notice',
            field=models.IntegerField(default=1, help_text='Notice period in months'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='termination_reasons',
            field=models.TextField(blank=True, default='Termination reasons here.', null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='contract_number',
            field=models.CharField(default='DEFAULT_CONTRACT', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='jurisdiction',
            field=models.CharField(default='Bahrain', max_length=100),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessee_cpr_number',
            field=models.CharField(default='000000000', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessee_name',
            field=models.CharField(default='Unknown Lessee', max_length=255),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessor_cr_number',
            field=models.CharField(default='174008-1', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessor_name',
            field=models.CharField(default='Platform Bahrain W.L.L', max_length=255),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='Default terms and conditions.', null=True),
        ),
    ]
