# Generated by Django 4.2 on 2024-12-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0003_leasecontract_actual_rent_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasecontract',
            name='business_incubator_number',
        ),
        migrations.RemoveField(
            model_name='leasecontract',
            name='monthly_rent_fee',
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='incubator_number',
            field=models.CharField(default='0151', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=70.0, max_digits=10, null=True),
        ),
    ]
