# Generated by Django 4.2 on 2024-12-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0004_remove_leasecontract_business_incubator_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='contract_duration',
            field=models.CharField(default='1 Year', max_length=50),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='contract_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='contract_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='package',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='actual_rent_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='dispute_resolution',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='incubator_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='incubator_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='jurisdiction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessee_authorized_signatory',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessee_commercial_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessee_commercial_registry_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessee_cpr_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessee_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessee_personal_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessee_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessor_authorized_signatory',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessor_cr_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessor_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='lessor_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='modification_terms',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='office_actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='payment_obligations',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='support_stop_notice',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='termination_reasons',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
