# Generated by Django 4.2 on 2024-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0005_leasecontract_contract_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasecontract',
            name='contract_duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='contract_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
