# Generated by Django 4.2 on 2024-12-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0006_alter_leasecontract_contract_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(default='', max_length=50, unique=True)),
                ('package', models.CharField(default='', max_length=255)),
                ('contract_duration', models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=100)),
                ('contract_effective_date', models.DateField(blank=True, null=True)),
                ('contract_expiration_date', models.DateField(blank=True, null=True)),
                ('actual_rent_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('business_incubator_number', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_rent_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('first_party_signatory_name', models.CharField(default='', max_length=255)),
                ('first_party_designation', models.CharField(default='', max_length=100)),
                ('first_party_signature_date', models.DateField(blank=True, null=True)),
                ('second_party_signatory_name', models.CharField(default='', max_length=255)),
                ('second_party_title', models.CharField(default='', max_length=100)),
                ('second_party_personal_id', models.CharField(blank=True, max_length=50, null=True)),
                ('second_party_commercial_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_party_commercial_registry_number', models.CharField(blank=True, max_length=50, null=True)),
                ('second_party_signature_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='contracts',
            index=models.Index(fields=['contract_number'], name='lamx_contra_contrac_7c17bc_idx'),
        ),
        migrations.AddIndex(
            model_name='contracts',
            index=models.Index(fields=['second_party_signatory_name'], name='lamx_contra_second__ab7c11_idx'),
        ),
    ]
