# Generated by Django 4.2 on 2024-12-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0007_contracts_contracts_lamx_contra_contrac_7c17bc_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaseContract',
        ),
    ]
