# Generated by Django 4.2 on 2024-12-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0010_contracts_id_alter_contracts_contract_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='id',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
