# Generated by Django 4.2 on 2024-12-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0011_remove_contracts_id_alter_contracts_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
