# Generated by Django 4.2 on 2024-12-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0013_remove_contracts_increment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='con_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
