# Generated by Django 4.2 on 2024-12-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0014_contracts_con_id_alter_contracts_contract_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='con_id',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
