# Generated by Django 4.2 on 2024-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0015_remove_contracts_con_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='monthly_rent_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
