# Generated by Django 4.2 on 2025-01-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0016_alter_contracts_monthly_rent_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='business_brief',
            field=models.FileField(blank=True, null=True, upload_to='uploads/business_brief/'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='company_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('existing', 'Existing')], default='startup', max_length=50),
        ),
        migrations.AddField(
            model_name='contracts',
            name='cpr_copy',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cpr_copy/'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='cr_copy',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cr_copy/'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='cr_extract',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cr_extract/'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='need_more_assistance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='payment_interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=50),
        ),
        migrations.AddField(
            model_name='contracts',
            name='second_party_commercial_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='second_party_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='second_party_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='second_party_signatory_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='second_party_title_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
