# Generated by Django 4.2 on 2025-01-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0017_contracts_business_brief_contracts_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contract_number',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
