# Generated by Django 4.2 on 2025-01-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0018_alter_contracts_contract_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIncubator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lamx.contracts')),
            ],
        ),
    ]
