# Generated by Django 4.2 on 2025-01-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0019_businessincubator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='business_incubator_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lamx.businessincubator'),
        ),
    ]
