# Generated by Django 4.2 on 2025-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0020_alter_contracts_business_incubator_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='business_incubator_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
