# Generated by Django 4.2 on 2025-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0023_alter_contracts_business_incubator_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessincubator',
            name='contract',
        ),
        migrations.AddField(
            model_name='businessincubator',
            name='contract_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
