# Generated by Django 4.2 on 2025-02-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0026_alter_contracts_business_incubator_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='first_party_designation_ar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contracts',
            name='first_party_signatory_name_ar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
