# Generated by Django 4.2.11 on 2025-02-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0028_alter_contracts_first_party_signatory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='first_party_designation',
            field=models.CharField(default='Partner', max_length=100),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='first_party_designation_ar',
            field=models.CharField(default='شريك', max_length=100),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='first_party_signatory_name',
            field=models.CharField(choices=[('Dr. ABDULLA AL HAMED', 'Dr. ABDULLA AL HAMED'), ('EYAD ABDULLA MOHAMED FAKHRI', 'EYAD ABDULLA MOHAMED FAKHRI')], default='John Doe', max_length=255),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='first_party_signatory_name_ar',
            field=models.CharField(choices=[('عبدالله ال حامد', 'عبدالله ال حامد'), ('إياد عبد الله محمد فخري', 'إياد عبد الله محمد فخري')], default='جون دو', max_length=255),
        ),
    ]
