# Generated by Django 4.2.11 on 2025-02-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0029_contracts_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='attachments',
        ),
    ]
