# Generated by Django 4.2.11 on 2025-02-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0030_remove_contracts_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
