# Generated by Django 4.2.11 on 2025-02-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0031_contracts_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='attachments',
        ),
    ]
