# Generated by Django 4.2.11 on 2025-02-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0032_remove_contracts_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Completed'), (3, 'Cancelled')], default=0, help_text='Contract status (0=Pending, 1=Active, 2=Completed, 3=Cancelled)'),
        ),
    ]
