# Generated by Django 4.2.11 on 2025-02-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0033_contracts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='status',
            field=models.IntegerField(choices=[(0, 'Under Review'), (1, 'Pending'), (2, 'Active'), (3, 'Cancelled'), (4, 'Active With SME Regisration')], default=0, help_text='Contract status (0=Pending, 1=Active, 2=Completed, 3=Cancelled)'),
        ),
    ]
