# Generated by Django 4.2.11 on 2025-02-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamx', '0034_alter_contracts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='first_party_signatory_name',
            field=models.CharField(choices=[('Dr. ABDULLA AL HAMED', 'Dr. ABDULLA AL HAMED'), ('EYAD ABDULLA MOHAMED FAKHRI', 'EYAD ABDULLA MOHAMED FAKHRI')], default='Dr. ABDULLA AL HAMED', max_length=255),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='first_party_signatory_name_ar',
            field=models.CharField(choices=[('عبدالله ال حامد', 'عبدالله ال حامد'), ('إياد عبد الله محمد فخري', 'إياد عبد الله محمد فخري')], default='عبدالله ال حامد', max_length=255),
        ),
    ]
