# Generated by Django 4.2.11 on 2025-03-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lamx", "0035_alter_contracts_first_party_signatory_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracts",
            name="sme_registration",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="pending",
                help_text="SME Registration Status (Pending, In Progress, Completed)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Under Review"),
                    (1, "Pending"),
                    (2, "Active"),
                    (3, "Cancelled"),
                ],
                default=0,
                help_text="Contract status (0=Pending, 1=Active, 2=Completed, 3=Cancelled)",
            ),
        ),
    ]
