# Generated by Django 4.2.11 on 2024-11-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='reporting_manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_manager', to='employee.employee', verbose_name='Reporting Manager'),
        ),
    ]
