# Generated by Django 4.2.11 on 2024-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeworkinformation_reporting_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(choices=[('Bahrain', 'Bahrain'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
