# Generated by Django 4.2.11 on 2024-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='grade',
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default='Grade 1', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default='Grade 1', max_length=10),
        ),
    ]
