# Generated by Django 4.2.11 on 2024-11-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employee_grade_employeeworkinformation_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='grade',
            field=models.CharField(choices=[('300', 'Grade 1 - BHD 300'), ('310', 'Grade 2 - BHD 310'), ('330', 'Grade 3 - BHD 330'), ('360', 'Grade 4 - BHD 360'), ('400', 'Grade 5 - BHD 400'), ('450', 'Grade 6 - BHD 450'), ('510', 'Grade 7 - BHD 510'), ('600', 'Grade 8 - BHD 600'), ('700', 'Grade 9 - BHD 700'), ('800', 'Grade 10 - BHD 800')], default='Grade 1', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='grade',
            field=models.CharField(choices=[('300', 'Grade 1 - BHD 300'), ('310', 'Grade 2 - BHD 310'), ('330', 'Grade 3 - BHD 330'), ('360', 'Grade 4 - BHD 360'), ('400', 'Grade 5 - BHD 400'), ('450', 'Grade 6 - BHD 450'), ('510', 'Grade 7 - BHD 510'), ('600', 'Grade 8 - BHD 600'), ('700', 'Grade 9 - BHD 700'), ('800', 'Grade 10 - BHD 800')], default='Grade 1', max_length=10),
        ),
    ]
