# Generated by Django 4.2.11 on 2024-11-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employeeworkinformation_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeworkinformation',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeworkinformation',
            name='grade',
        ),
    ]
