# Generated by Django 4.2.11 on 2024-11-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_employeeworkinformation_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.PositiveIntegerField(choices=[(1, 'Grade 1: 0 BHD'), (2, 'Grade 2: 322 BHD'), (3, 'Grade 3: 327 BHD'), (4, 'Grade 4: 348 BHD'), (5, 'Grade 5: 377 BHD'), (6, 'Grade 6: 420 BHD'), (7, 'Grade 7: 467 BHD'), (8, 'Grade 8: 526 BHD'), (9, 'Grade 9: 616 BHD'), (10, 'Grade 10: 768 BHD')], default=2),
        ),
    ]
