# Generated by Django 4.2.11 on 2024-11-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_employee_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(verbose_name='Step')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='employee.grade', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Grade Step',
                'verbose_name_plural': 'Grade Steps',
                'ordering': ['grade', 'step'],
                'unique_together': {('grade', 'step')},
            },
        ),
    ]
