# Generated by Django 4.2.11 on 2024-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_gradestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='step',
            field=models.PositiveIntegerField(default=1, help_text='Select the grade step', verbose_name='Step'),
        ),
    ]
