# Generated by Django 4.2.11 on 2024-11-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employee_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradestep',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='gradestep',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.PositiveIntegerField(choices=[(2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (300, 'Grade 1')], default=2),
        ),
    ]
