# Generated by Django 4.2.11 on 2024-11-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_employee_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='grade',
            field=models.PositiveIntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10')], default=1),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='step',
            field=models.PositiveIntegerField(default=1, help_text='Select the grade step', verbose_name='Step'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='grade',
            field=models.PositiveIntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10')], default=1),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='step',
            field=models.PositiveIntegerField(default=1, help_text='Select the grade step', verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.PositiveIntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10')], default=1),
        ),
    ]
