# Generated by Django 4.2.11 on 2024-11-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_employeeworkinformation_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='step',
        ),
    ]
