# Generated by Django 4.2.11 on 2024-12-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_remove_employee_grade_remove_employee_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeworkinformation',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='employeeworkinformation',
            name='step',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeworkinformation',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeworkinformation',
            name='step',
        ),
    ]
