# Generated by Django 4.2 on 2024-12-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmx', '0002_crmrecord_remove_lead_customer_delete_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmrecord',
            name='address',
        ),
        migrations.RemoveField(
            model_name='crmrecord',
            name='state',
        ),
        migrations.AddField(
            model_name='crmrecord',
            name='area',
            field=models.CharField(blank=True, help_text='Area name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crmrecord',
            name='block',
            field=models.CharField(blank=True, help_text='Block number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crmrecord',
            name='building',
            field=models.CharField(blank=True, help_text='Building number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crmrecord',
            name='road',
            field=models.CharField(blank=True, help_text='Road number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crmrecord',
            name='city',
            field=models.CharField(default='Manama', help_text='City name (e.g., Manama, Muharraq)', max_length=100),
        ),
        migrations.AlterField(
            model_name='crmrecord',
            name='country',
            field=models.CharField(default='Bahrain', help_text='Default is Bahrain', max_length=100),
        ),
    ]
