# Generated by Django 4.2 on 2024-12-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmx', '0003_remove_crmrecord_address_remove_crmrecord_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmrecord',
            name='industry',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('finance', 'Finance'), ('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('transportation', 'Transportation'), ('retail', 'Retail'), ('construction', 'Construction'), ('technology', 'Technology'), ('energy', 'Energy'), ('consulting', 'Consulting'), ('pharmaceutical', 'Pharmaceutical'), ('media', 'Media'), ('telecommunications', 'Telecommunications')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crmrecord',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed'), ('inactive', 'Inactive'), ('in_progress', 'In Progress'), ('follow_up', 'Follow Up'), ('awaiting_response', 'Awaiting Response'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
