# Generated by Django 4.2.11 on 2024-11-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='field',
            field=models.CharField(blank=True, choices=[('nationality', 'nationality'), ('children', 'Children'), ('marital_status', 'Marital Status'), ('experience', 'Experience'), ('employee_work_info__experience', 'Company Experience'), ('gender', 'Gender'), ('country', 'Country'), ('state', 'State'), ('contract_set__pay_frequency', 'Pay Frequency'), ('contract_set__wage_type', 'Wage Type'), ('contract_set__department__department', 'Department on Contract')], help_text='The related field of the employees', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='field',
            field=models.CharField(blank=True, choices=[('nationality', 'nationality'), ('children', 'Children'), ('marital_status', 'Marital Status'), ('experience', 'Experience'), ('employee_work_info__experience', 'Company Experience'), ('gender', 'Gender'), ('country', 'Country'), ('state', 'State'), ('contract_set__pay_frequency', 'Pay Frequency'), ('contract_set__wage_type', 'Wage Type'), ('contract_set__department__department', 'Department on Contract')], help_text='The related field of the employees', max_length=255, null=True),
        ),
    ]
