# Generated by Django 4.2.11 on 2024-11-12 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('biometric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricemployees',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
