# Generated by Django 4.2.11 on 2024-11-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0002_alter_biometricemployees_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevices',
            name='zk_password',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
