# Generated by Django 4.2.11 on 2025-01-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0003_biometricdevices_zk_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdevices',
            name='machine_type',
            field=models.CharField(choices=[('zk', 'ZKTeco Biometric'), ('anviz', 'Anviz Biometric'), ('cosec', 'Matrix COSEC Biometric'), ('dahua', 'Dahua Biometric')], max_length=18, null=True),
        ),
    ]
