# Generated by Django 4.2.11 on 2025-01-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0004_alter_biometricdevices_machine_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biometricdevices',
            old_name='cosec_password',
            new_name='bio_password',
        ),
        migrations.RenameField(
            model_name='biometricdevices',
            old_name='cosec_username',
            new_name='bio_username',
        ),
    ]
