# Generated by Django 4.2.11 on 2025-01-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0005_rename_cosec_password_biometricdevices_bio_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricemployees',
            name='dahua_card_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biometricdevices',
            name='bio_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='biometricdevices',
            name='bio_username',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='biometricdevices',
            name='machine_ip',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
