# Generated by Django 4.2 on 2025-01-29 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_remove_employeeworkinformation_grade_and_more'),
        ('biometric', '0006_biometricemployees_dahua_card_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricemployees',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='biometricemployees',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='User ID'),
        ),
    ]
