# Generated by Django 4.2 on 2025-01-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceovertime',
            name='year',
            field=models.CharField(default='2025', max_length=10, null=True, verbose_name='Year'),
        ),
    ]
